Add status, upgrade, and some other minor things
addiva-elektronik/netconf-client pull request #6
Opened 2024-06-10 23:25 UTC by troglobit

This PR adds some new functionality for customers:

 - Add get-data RPC to read operational status for interface counters and firmware version
 - Add edit-config RPC and separate copy-config RPCs for setting config to specific datastore
 - Add upgrade support using the Infix install-bundle RPC
 - Add HTML server to ease device upgrade
 - Add Status bar to bottom, for showing status and errors
 - Refactor main view, Send button felt malplaced in the right pane, now under text area
 - Refactor default Send command handling to allow custom NETCONF RPC commands
 - Refactor right-hand pane a bit, add text entry labels
 - Add Find Device button to Connection Parameters, locates all NETCONF capable mDNS devices
 - Refactor main menu a bit, rename entries, simplify zoom, add common keybindings
 - Add Help menu with About, License, and Usage Guide (html viewer) dialog boxes

It's probably more, but that's a good overall summary.

2024-06-10 23:30 UTC, troglobit commented
**Note:** I haven't added any GitHub action for building and packaging yet.  I played around a bit with it in https://github.com/troglobit/webby/ just to learn, but I never managed to get the Windows packaging to work (always were missing some DLL files).

Also, packaging was not possible in this project due to the missing profinet XML files.  I added a suggestion in the Usage Guide for keeping two such example files in-tree without worrying about revealing names of any end customer.

2024-06-11 06:57 UTC, troglobit commented
Sorry, found (and fixed) an unhandled exception when I started testing on Windows[^1], hence the new late commits.  

[^1]: nothing professional, I got it working with "Git Bash" on Windows 10.

2024-06-11 07:53 UTC, saba8814 approved these changes
BRA JOBBAT!

2024-06-11 08:41 UTC, troglobit commented
> BRA JOBBAT!

Tackar! 😅

2024-06-11 08:57 UTC, mattiaswal requested changes
Great work, just minor things. 

except Exception, 
Exception is redundant, since only except will catch all exceptions

2024-06-11 08:57 UTC, mattiaswal commented on main.py
> +        except Exception:
Drop Exception:
except:

2024-06-11 08:57 UTC, mattiaswal commented on main.py
> +        except Exception:
Drop Exception:
except:

2024-06-11 08:57 UTC, mattiaswal commented on main.py
> +        except Exception:
Drop Exception:
except:

2024-06-11 08:57 UTC, mattiaswal commented on main.py
> +        except Exception:
Drop Exception:
except:

2024-06-11 09:02 UTC, troglobit commented
> except Exception, Exception is redundant, since only except will catch all exceptions

Ah of course, will fix asap, asap!

2024-06-11 09:09 UTC, mattiaswal approved these changes

2024-06-11 09:09 UTC, merged